version: 2.1

orbs:
  python: circleci/python@3.1.0

jobs:
  check_env:
    docker:
      - image: cimg/python:3.10
    steps:
      - run:
          name: check pwd
          command: pwd
      - run:
          name: Check dir contents
          command: ls -altr

  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    executor: python/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: pytest test_hello_world

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
