# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Standard CCI processes
orbs:
  python: circleci/python@3.1.0

# Define the jobs to be invoked in the workflow - basically the command/scripts that need to be run in the workflow
jobs:
  #tasks
  build:
    executor: python/default
    steps:
      - python/install-packages:
          pkg-manager: pip
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    executor: python/default
    steps:
      - checkout #fetch the source code
      - attach_workspace:
          at: .      
      - run:
          name: Run Tests
          command: pytest test_hello_world

#workflow ot be executed
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build