version: 2.1

orbs:
  python: circleci/python@3.1.0

jobs:
  build_and_test:
    #executor: python/default
    docker:
      - image: cimg/python:3.11-browsers
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Flask in background
          command: |
            export FLASK_APP=hello_world.py
            set -x
            flask run --host=0.0.0.0 & 
            #Wait until the server is accessible
            for i in {1..30}; do
              if curl --fail http://127.0.0.1:5000; then
                echo "Flask server is up!"
                break
              fi
              echo "Waiting for Flask server..."
              sleep 1
            done
      - run:
          name: Run Tests
          command: pytest test_hello_world.py -v

workflows:
  build_and_test:
    jobs:
      - build_and_test
