version: 2.1

orbs:
  python: circleci/python@3.1.0
  browser-tools: circleci/browser-tools@1.5.3
jobs:
  build_and_test:
    docker:
      # Use an ARM64-compatible image
      - image: cimg/python:3.12
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Check versions
          command: |
            google-chrome --version
            chromedriver --version          
      - run:
          name: Install dependencies
          command: |
            pip3 install -r requirements.txt
      - run:
          name: Run Flask in background
          command: |
            export FLASK_APP=hello_world.py
            flask run --host=0.0.0.0 --port=5000 &
            sleep 3
      - run:
          name: Check if Flask is listening
          command: lsof -i :5000 || echo "Port 1234 is not open"
      - run:
          name: Test connectivity
          command: |
            # Check if Flask is running
            curl -s http://localhost:5000 || echo "Flask is not running"
      - run:
          name: Run Tests
          command: |
            # Run tests with detailed output
            pytest test_hello_world.py

workflows:
  build_and_test:
    jobs:
      - build_and_test
