version: 2.1

orbs:
  python: circleci/python@3.1.0

jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install pytest
          command: pip install pytest
      - run:
          name: Install Silenium
          command: pip install selenium
      - run:
          name: Run Tests
          command: pytest test_hello_world.py

workflows:
  build_and_test:
    jobs:
      - build_and_test: 
