version: 2.1

orbs:
  python: circleci/python@3.1.0

jobs:
  build_and_test:
    #executor: python/default
    docker:
      - image: cimg/python:3.11-browsers
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run App in background
          command: |
            python hello_world.py & 
            sleep 3
      - run:
          name: Run Tests
          command: pytest test_hello_world.py

workflows:
  build_and_test:
    jobs:
      - build_and_test
