version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.5.3

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10-browsers

jobs:

  # Build Job
  build:
    docker:
      # Use an ARM64-compatible image
      - image: cimg/python:3.10-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      
      # Verify browser versions for debugging
      - run:
          name: Check versions
          command: |
            google-chrome --version
            chromedriver --version          

      # Install Python dependencies
      - run:
          name: Install dependencies
          command: |
            pip3 install -r requirements.txt
  
  # Test Job
  test:
    executor: python-executor
    steps:
      # Run pytest and capture logs
      - run:
          name: Run Test and Capture Logs
          command: |
            flask run --host=0.0.0.0 --port=5000 &
            pytest test_hello_world.py > test_results/test_output.log 2>&1

      # Store test results and artifacts
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results

  # Mock Deploy Staging
  deploy-staging:
    executor: python-executor
    steps:
      - run:
          name: Deploy Cluster 1
          command: echo "Successfully Deployed to Staging Cluster 1"
      - run:
          name: Deploy Deploy 2
          command: echo "Successfully Deployed to Staging Cluster 2"

  # Mock Deploy Prod
  deploy-prod:
    executor: python-executor
    steps:
      - run:
          name: Deploy Prod 1
          command: echo "Successfully Deployed to Prod Cluster 1"
      - run:
          name: Deploy Prod 2
          command: echo "Successfully Deployed to Prod Cluster 2"

# Setting up the workflow
workflows:
  prod_run:
    jobs:
      - build
      - test:
          requires:
            - build      
      - deploy-staging:
          requires:
            - test
      - deploy-prod:
          requires:
            - test